branch-defaults:
  develop:
    environment: br-tr-dev
    group_suffix: null
  master:
    environment: br-tr-dev
environment-defaults:
  br-tr-dev:
    branch: null
    repository: null
global:
  application_name: br-tr
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  repository: null
  sc: git
